package:
  name: pyside2-tools
  version: 0.0.0

source:
  git_url:  http://codereview.qt-project.org/pyside/pyside-tools
  git_tag: dev


requirements:
  build:
    - cmake
    - qt 5.6.2
    - python
    - pyside2
  run:
    - qt 5.6.2
    - python
    - pyside2

build:
  number: 0

#test:
#  commands:
#    - shiboken --help
#  imports:
#    - shiboken

about:
    home: https://github.com/PySide/Tools
    license: LGPL
