package:
  name: pyside2
  version: 0.0.0

source:
  git_url: http://codereview.qt-project.org/pyside/pyside
  git_tag: dev

build:
  number: 0

requirements:
  build:
    - cmake     [unix]
    - qt 5.6.2  [unix]
    - libpng    [linux]
    - shiboken2 [unix]
    - python
  run:
    - qt 5.6.2  [unix]
    - shiboken2 [unix]
    - libpng    [linux]
    - python
    - python.app  [osx]

about:
  home: https://pypi.python.org/pypi/PySide
  license: LGPL
