package:
  name: shiboken2
  version: 0.0.0

source:
  git_url: http://codereview.qt-project.org/pyside/shiboken
  git_tag: dev

requirements:
  build:
    - cmake
    - qt 5.6.2
    - python
  run:
    - qt 5.6.2
    - python

build:
  number: 0

test:
  commands:
    - shiboken2 --help
  imports:
    - shiboken2

about:
    home: https://github.com/PySide/Shiboken
    license: LGPL
